server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
    rest:
      base-path: /api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(OS0zoyIY0KujXWAuyV5+If9fJxHfcFr8MQ3crTvdHk9TKDfRimBA7LYbXfdojPiOPIUYfX58K87fvACzWF+xpNzlcAeBb1L8bfsWYnkK5U8=) # Database이름 ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: ENC(vVay1/MAok/zRMNXzQEptFIkYEkoX8zwFE1dy7Tm0TShxoH65O4jTfRNdS4ezmL5)
    password: ENC(cG9jBg9WiScebGcMK09PxfQWi16K5E1HSHW77gt4RxDQo0wU2Sp12WUd/kJgXSqn)

  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true


jasypt:
  password : ${JASPYT_PASSWORD}
  encryptor:
    bean: jasyptEncryptor