spring:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/masterdb
        read-only: false
        username: root
        password: 1234
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3307/masterdb
        read-only: true
        username: root
        password: 1234

#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jwt:
    secret: ENC(fEJ7WA7eRGVpVlO/l1AxQxWrxdKrckoBlTwDPfYVm6+aWYyMV48weamOful1HUsovIXEGhAonBKbRrlrJRiDw2tB4Bc8zGIBSN7yBjb9nM8=)
    token-prefix: ENC(LtV6ZJrgUovD3gbWplYf3FSYiu818pv1S9Mc+xERD9DHuxma96sQpui/A9PNYq7V)
    haeder-refresh: ENC(A1BFSNQYpjOK6DnCL+Yz7wWE2vpUZOy+2pW8KgYTmt4eSvwoTYOrkaseK+/ebKIa)
    haeder-access: ENC(XmDnf2JrFvZvt6kO4AygGf7jRdch2p9tXbLti9N91XcI0WY/+hP+zBZEsjWUUEbo)

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          kakao:
            client-id: ENC(CoMySNX2PMaZbR7nl9XtPITWRHrB+kClg06+bQSJw2lziuiJ8TZwW4SEK7r77oie/Kp3zS0ypWllwYYjG4rvloMu3IHjHdsmpxnWrkodEH8=)
            client-secret: ENC(fpZjJAjfzDlkAgvwfuOQLu7rkhPMxO8f08uVQKn3sJQdufz7f+JMtNOOysi9mIuN16KvpsqNep2hwfGWazZpMUUDwdncNvYjMHLyTOBxIcs=)
            client-authentication-method: ENC(tRG2nwDDCP/8D6b16M+xayfJGPtTwQtBGnGFW2CLeOgZFF3U+Yx/KbKdVOCOn2NqR+zuSSPWwP/634Zy0pZXRw==)
            redirect-uri: ENC(HmWjXpj9PgLTtN7P/bc4ywJy875XimNb2JzGt13XkdZWWCIb85ysYluPyMCADraBmV0HW1/+KT9vE1ogRgNhjVextA633mgpn26jvkEQoRqxiU7ZsfWx6qABCq29MWj8)
            authorization-grant-type: ENC(V6kwdUnoVuOOU/Xa/yxKp1Q9bHRZgHCc2WV1kbjDgmD7KJ6EFDZUa3dsy9MwByXfX3S0Rd8gld1/3mM7AYVHjQ==)
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
          google:
            client-id: ENC(cp0wTf1cyx0Tq6l7zTPzjT+Mr1cMnJCsRds7TmJlkkN9UdQC+4/QpQ1Hbvqj3zmZRAXoKIFE9F9gHXxYajtfh0hw7593Uz4gAgrU9IwBc93nQdcLUg1PU95Im5b2OfEEi++YMRp+VQFXfgDSUflEnA==)
            client-secret: ENC(YeGsv3GO35C06UO4GGyxUTLJDWg9mg6FckA4gu8rGo4W8D0vRhvja4bIdl7jp0B1W7XBcd8AjRsrI5uDaIGk8jEDMhxlyakL5airTrvMPvk=)
            redirect-uri: ENC(hGwrwsTFBebK4RyJLLBsnz5HxWdUvOsb9BWxDesHSeuAlevmRuWgp/WEhPz0HHex1FYmpN33BtLNtdBgGTjoyVHnNjcJObCmOVTUSOen3i06XLyAx/HSemWxcEZieHNU)
            scope:
              - email
              - profile
          naver:
            client-id: ENC(nLSf4y/SsZVsQJyDaEAhgDWn2EcrQTKSuBTUcwD6eJaSxdkzaZewSV8nyQiCWUC8TiH3+iJZPT2Y/XGwjYAPCQ==)
            client-secret: ENC(GzzqKKQ+9avO16JF02njfLMeK5KX/bIsFge+zVvdLHbo6hE1gzbv1/wFzEh1aR6l)
            redirect-uri: ENC(H/UlXpmFm5wWGgtP4F/6UucMHMxQ6SRebbuuLsjx0d0i9MdXyqm0Mr0JnnFbh8Wf6Vq4FjSvIVoI87zsSjQ+VxqyspUH8KkFo0vpcCfZRDl2yS7XyAUIGUJa1PPqKfS1)
            authorization-grant-type: authorization_code
            client-name: naver
            scope:
              - name
              - email
