server:
  port: 8081
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
    rest:
      base-path: /api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(OS0zoyIY0KujXWAuyV5+If9fJxHfcFr8MQ3crTvdHk9TKDfRimBA7LYbXfdojPiOPIUYfX58K87fvACzWF+xpNzlcAeBb1L8bfsWYnkK5U8=) # Database이름 ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql에 생성한 사용자 계정 정보를 써야 합니다.
    username: ENC(vVay1/MAok/zRMNXzQEptFIkYEkoX8zwFE1dy7Tm0TShxoH65O4jTfRNdS4ezmL5)
    password: ENC(cG9jBg9WiScebGcMK09PxfQWi16K5E1HSHW77gt4RxDQo0wU2Sp12WUd/kJgXSqn)

  # spring data jpa 설정
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jwt:
    secret: ENC(OAdLW8Ke/pyGKNDSTMQ6b/XgpsboFinNPnFmjXShoFcgsHyEKxYGuaNGO0/GP3x83IGirgjZ+uussPFpdmC0Jmc9Qb4sfxXjmFbmAh0bkPk=)
    token-prefix: ENC(bu++C9y7w4zu3jmpl4haFTwDeXThrfG11Y3PaRfxkFzazYFA1y6OCfY/lZLHeBXA)
    haeder-refresh: ENC(ek+bV+9dfga4OzTewkRo7nX3sxYV9//I1AUNghyq5SEjJ5ZBTeVPfB/lciTx7ybQ)
    haeder-access: ENC(fLx2ZMxKjjyesC27zZL/w792B1yAVTK5qnpFW/tgV9pOfP13rODpNl/nvZ8Wnx1c)

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: ENC(abV4Bdjb0qfv5YEFbQkSMq3/0xgohgvpa/rnguJnDN3QP8+gXdqq+tE32mV1qOZ1/jPg9Xt8sJsBmaKP2X1MAvjmPLdOUi9Kx2QakFH92Sw=)
            token-uri: ENC(NSGItl4nKbZ+/lr5GQ/vrHzvnV7ncolwHyp++e2ekWk2SyLsG4OH0Rp24H6c8tpzA3if0+mlDOecphrkuCQsQakJTttmmATQ3roprEPYov8=)
            user-info-uri: ENC(U0S/bSOF8IAZRsfzfR+hl8etp/th69rbCEI7FHFb6xmTbetYmjl/swUyMoCdjfszJKZ8CDYcGTcTl7rjIQHPwU0nQXWazHf56wxNiQw0EvA=)
            user-name-attribute: id
          naver:
            authorization-uri: ENC(9qu0z2Tc/NZKinEW7QPCxMBLA0sq2AGzce3Wu7SZOAhNlFncN73GuHLmMvuI5Zr4wRb8s639AaQvMDv8O+sTiEaGAmKwggwRk8T4WRx+G10=)
            token-uri: ENC(8AwDlmpYoXnZWsXrcfXWPebq5W22FbBEu6o4j4Yuq6E7W7oLzjwZkLyRezK/lffwava9dsZBgAV0KPYC+dnLUgkjT3VjiO+gcWVjHAqkM7o=)
            user-info-uri: ENC(y8Uh0v8pWj9aGW3JMxNZxOvlOfZ51YpfU6ob8/7X1Wv0oF6WyxaF3p+UCFLB3rPEO68QTYcrA0A5qGTQTQnVv+LRKANl8+geyi5C+FCjFlg=)
            user-name-attribute: response
        registration:
          kakao:
            client-id: ENC(1B6M9jx922aR/BW+79Qc7DzKcqw0A1gmCgELay9fE40qhC5s5f+sFjT6fFzeOk+0Jq3ePiDeWT0QgqIvvmPp/YzdaSnu1SdC0CYE6EvEL0U=)
            client-secret: ENC(+vU7rcbgVhv5oBaaE6vJm0IZHEMIn+JEq6l5xwPVEbCM0L7x7AHf36G7n9PAZPN3wf7lKZcbljks33Fjd9kySR6injmKDOe31zFutkF6k04=)
            client-authentication-method: ENC(XqpkUuwSmD7b+N/1eadLjaZnGnvoo67sOmnVYuXz6cnVDkctYc1LbYrginLx7bPIKdUYb10ZPNLn9oQOfnfQQg==)
            redirect-uri: ENC(0rzP60GsbuEFf3Occk6R0mSnYWTVYMmKW4ttCXxfM6abwzmP16Z8SoF/IVWmdQJg1rjEBZZ5xp+L2UF594rivCOgyr2cIiFDD33Abp3dMu8=)
            authorization-grant-type: ENC(C6CFq2RAOmE04CWKthR5kmxkqS1KCThTZImpFDqGztdVc/8NEPG1N/WuS1qjDBD2ipinkSb6FXKybqBzwy3f8Q==)
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - gender
              - age_range
          google:
            client-id: ENC(RImpFhH40nuFYBcsnFopx7wxNUbvRidnh3VEj+snsQt53Lxe9jbqPGTwTt+yavMJdSuFuhM+vLIgHGxTAsXVn9Gf26Wrht1PoAPvR8OiigZGE/aOESRm5kjS8Ha2sZ1r2hCdNeBzKcrHjalgJbzHhQ==)
            client-secret: ENC(v96a4tJNlaF71/24oP3b3QGVSuHM2Vw8Qf9WZyJU6MU7gq6IHdiZhi3GWHvTOy/F+9frg+nKIOOxk/KDgkdzkUtb7gzjcWt1c3bcH2g8XAE=)
            redirect-uri: ENC(13X1jvMogtALwwSFnS7OsvlQ6c/ML/JOQ+qWbHs6WgAB0BwAvi5IwU+Mr9hwZnLFx8PIfyeOrj2W6pB51/TNn6s4UCDtrg6K4PEVOHKOckM=)
            scope:
              - email
              - profile

jasypt:
  password : ${JASYPT_PASSWORD}
  encryptor:
    bean: jasyptEncryptor